### ISSUE TITLE
插件不生效

### ISSUE THREAD

**Issue by huangjianyi0701** [elazarcoh/simply-view-image-for-python-debugging#66]
安装了插件，但是不生效，也重装了vscode，请问这是什么原因呢？
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/129131129/fd9dc7df-6cf5-4939-adfe-e622e6d3c208)
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/129131129/195934c2-4bd0-4864-ab9e-5eb456fa6fed)

**Comment by elazarcoh** [comment]
English please

**Comment by huangjianyi0701** [comment]
> English please
I installed the plugin, but it doesn't work, and I also reinstalled vscode.

**Comment by elazarcoh** [comment]
There might be few reasons. 
First, I'm advising you to test it in a minimal example:
```python
import numpy as np

# gradient image
N = 100
img = np.arange(N*N).reshape(N,N).astype(np.float32)

print("done")  # put a breakpoint here and try to view `img`
``` 

Additionally, look for the logging under **Output -> View Image for Python** (you might need to enable logging view settings: `svifpd.debug`). Please attach the log.

**Comment by huangjianyi0701** [comment]
> There might be few reasons. First, I'm advising you to test it in a minimal example:
> 
> ```python
> import numpy as np
> 
> # gradient image
> N = 100
> img = np.arange(N*N).reshape(N,N).astype(np.float32)
> 
> print("done")  # put a breakpoint here and try to view `img`
> ```
> 
> Additionally, look for the logging under **Output -> View Image for Python** (you might need to enable logging view settings: `svifpd.debug`). Please attach the log.

Error message display：
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/129131129/700dcfb3-cbac-457b-bd77-14eb876d04dc)

**Comment by huangjianyi0701** [comment]
> > There might be few reasons. First, I'm advising you to test it in a minimal example:
> > ```python
> > import numpy as np
> > 
> > # gradient image
> > N = 100
> > img = np.arange(N*N).reshape(N,N).astype(np.float32)
> > 
> > print("done")  # put a breakpoint here and try to view `img`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Additionally, look for the logging under **Output -> View Image for Python** (you might need to enable logging view settings: `svifpd.debug`). Please attach the log.
> 
> Error message display： ![image](https://user-images.githubusercontent.com/129131129/281322385-700dcfb3-cbac-457b-bd77-14eb876d04dc.png)

Using your example is fine, but in my own code I get this error and the "yellow bulb" doesn't appear!

**Comment by elazarcoh** [comment]
Ok. this means the "setup" of the extension in the debug doesn't work. If you can attach the logs, this can be helpful to debug it.

**Comment by huangjianyi0701** [comment]
> Ok. this means the "setup" of the extension in the debug doesn't work. If you can attach the logs, this can be helpful to debug it.

感谢您的答复，日志信息如下：

**Comment by elazarcoh** [comment]
Please attach the entire log. There might be a clue of why it's not working.
Also, please share more relevant information like:
OS
Python version
etc.

**Comment by huangjianyi0701** [comment]
windows11,locally,python version is 3.9.13,log information is below:
[Uploading test.log…]()

**Comment by huangjianyi0701** [comment]
> windows11,locally,python version is 3.9.13,log information is below: Uploading test.log…

I'm not sure if you can see my log file, a screenshot of the full log is below, thanks a lot!
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/129131129/c1372caf-49b1-46c1-b760-779be922c213)

**Comment by elazarcoh** [comment]
Can you upload the file?
Also, can you change the debug level to `verbose`?
In the meantime (few days...), I'll try to push a version which *might* improve the "setup", which is probably the cause.

**Comment by huangjianyi0701** [comment]
> Can you upload the log in a file? Also, can you change the debug level to `verbose`? In the meantime (few days...), I'll try to push a version which _might_ improve the "setup", which is probably the cause.

[test.log](https://github.com/elazarcoh/simply-view-image-for-python-debugging/files/13295243/test.log)

**Comment by huangjianyi0701** [comment]
> > Can you upload the log in a file? Also, can you change the debug level to `verbose`? In the meantime (few days...), I'll try to push a version which _might_ improve the "setup", which is probably the cause.
> 
> [test.log](https://github.com/elazarcoh/simply-view-image-for-python-debugging/files/13295243/test.log)
Also I would like to ask how to set up your plugin not to be able to use this button to save directly as a log?

**Comment by elazarcoh** [comment]
> > > Can you upload the log in a file? Also, can you change the debug level to `verbose`? In the meantime (few days...), I'll try to push a version which _might_ improve the "setup", which is probably the cause.
> > 
> > [test.log](https://github.com/elazarcoh/simply-view-image-for-python-debugging/files/13295243/test.log)
> 
> Also I would like to ask how to set up your plugin not to be able to use this button to save directly as a log?
> ![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/129131129/94308cb5-396c-472a-9ea5-470caa0c0939)
> 

I wasn't aware of this feature. I'll look it out.

**Comment by huangjianyi0701** [comment]
> > > > Can you upload the log in a file? Also, can you change the debug level to `verbose`? In the meantime (few days...), I'll try to push a version which _might_ improve the "setup", which is probably the cause.
> > > 
> > > 
> > > [test.log](https://github.com/elazarcoh/simply-view-image-for-python-debugging/files/13295243/test.log)
> > 
> > 
> > Also I would like to ask how to set up your plugin not to be able to use this button to save directly as a log?
> > ![image](https://user-images.githubusercontent.com/129131129/281359425-94308cb5-396c-472a-9ea5-470caa0c0939.png)
> 
> I wasn't aware of this feature. I'll look it out.

Thanks, looking forward to the results of your troubleshooting

**Comment by elazarcoh** [comment]
I pushed a pre-release version, 3.0.13. Please check it out.
If there are still issues, please let me know. I've added a bit more information to debug this kind of issues.

**Comment by huangjianyi0701** [comment]
> I pushed a pre-release version, 3.0.13. Please check it out. If there are still issues, please let me know. I've added a bit more information to help debug this kind of issues.

![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/129131129/45aea1cb-4d59-4d10-a10f-aec7855daa4f)
Is the plugin not updated yet? It looks like version 3.0.12 on my end

**Comment by elazarcoh** [comment]
use the "switch pre-release version"

**Comment by huangjianyi0701** [comment]
> use the "switch pre-release version"

It still doesn't seem to work, the output log is as follows
[test.log](https://github.com/elazarcoh/simply-view-image-for-python-debugging/files/13306271/test.log)

**Comment by elazarcoh** [comment]
The last line of the log indicates that the setup has succeeded. This means, that if you look in the variables list in VSCode debug view, you should be able to see a variable named `_python_view_image_mod` (It should be under Global). 
You can expand it and inspect it's content. If something isn't right, it's content should be empty. Please check it out and let me know. 
Preferably, attach an image with this variable content.

**Comment by huangjianyi0701** [comment]
> The last line of the log indicates that the setup has succeeded. This means, that if you look in the variables list in VSCode debug view, you should be able to see a variable named `_python_view_image_mod` (It should be under Global).
> You can expand it and inspect it's content. If something isn't right, it's content should be empty. Please check it out and let me know.
> Preferably, attach an image with this variable content.

unfortunately, under global I don't see the parameter "_python_view_image_mod"
